@startuml general_docking_algorithm
' !theme spacelab
scale 1

start

group Dokowanie

repeat 
backward: Jedź do przodu;
repeat while (abs(LR-LF) > epsilon) is (tak) not (nie)


if (min_distance < LF < max_distance) then (nie)
    repeat
    'backward:test;

    if (FL <  min_distance) then (tak)
        :obrót w prawo;
        :cofnij;
        :obrót w lewo;
        :podjedź do przodu;
    elseif (FL > max_distance) then (tak)
        :obrót w lewo;
        :cofnij;
        :obrót w prawo;
        :podjedź do przodu;
    endif

    repeat while (min_distance < LF < max_distance) is (nie) not (tak)
    'break
else (nie)
endif 
->;

:Ostateczny podjazd do ścianki przeciwległej; 

repeat
repeat while (min_distance < FL < max_distance) is (nie) not (tak)

end group

note
LF = lewy przedni czujnik odległości
LR = lewy tylny czujnik odległości

FR = przedni prawy czujnik odległości
FL = przedni lewy czujnik odległości
end note

end

@enduml